### ISSUE TITLE
Misplaced U+A6F0 BAMUM COMBINING MARK KOQNDON

### ISSUE THREAD

**Issue by dscorbett** [notofonts/bamum#1]
### Font
NotoSansBamum-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansBamum-unhinted.zip
Date: 2018-06-30

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The Phase F characters of Bamum can take U+A6F0 BAMUM COMBINING MARK KOQNDON, but as none of the glyphs in Bamum Supplement have anchor points, it is incorrectly positioned far to the right.

### Character data
𖨩꛰𖨪
U+16A29 BAMUM LETTER PHASE-F SHO
U+A6F0 BAMUM COMBINING MARK KOQNDON
U+16A2A BAMUM LETTER PHASE-F PUAE

### Screenshot
![𖨩꛰𖨪](https://user-images.githubusercontent.com/1124347/42129177-0fc34cee-7c8b-11e8-8eb5-f60a33767171.png)

**Comment by simoncozens** [comment]
Yes, confirmed in L2/09-102:

> In particular Phase F texts use U+A6F0 BAMUM COMBINING MARK KOQNDON rather widely.

Slightly more concerning is the fact that the phase *G* letters can take koqndon:

>  U+A6F0 bamum combining mark koqndon may be applied to any of the 80 letters.

and we have no anchor for that either.
