### ISSUE TITLE
Inconsistent weights of Bamum glyphs

### ISSUE THREAD

**Issue by dscorbett** [notofonts/bamum#2]
### Font
NotoSansBamum-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansBamum-unhinted.zip
Date: 2018-06-30

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The glyphs in the Bamum block are noticeably heavier than those in Bamum Supplement, which is a problem because characters from both blocks are used together in the Phase F edition of the script.

### Character data
𖨬ꛛ𖨭
U+16A2C BAMUM LETTER PHASE-F WA
U+A6DB BAMUM LETTER NA
U+16A2D BAMUM LETTER PHASE-F LI

### Screenshot
![𖨬ꛛ𖨭](https://user-images.githubusercontent.com/1124347/42136050-adb00658-7d22-11e8-925b-ed2a4e520dc0.png)

**Comment by simoncozens** [comment]
More to the point, the syllabic glyphs vary in weight across the weight axis but the Supplemental glyphs do not! But I sort of see a logic in that - living scripts in Noto get multiple weights whereas historical scripts get one weight, and here we have a combination of a living and a historical script.

The regular weight of the syllabic glyphs is correct, so if anything the logographs would need to be thickened up to match. But that would cause design problems; there's not much more room to add weight to them. I'm not sure what a good way forward on this is.

**Comment by simoncozens** [comment]
I'm going to say this can't be done without redrawing the whole font, which we won't do for a historical script which works fine in regular, or by removing the variation which we won't do for a living script. So there is *no* good way forward.
